### ISSUE TITLE
Elements displayed are not all in red colored text.

### ISSUE THREAD

**Issue by myerssr** [yousefaltufiel/Elemental#1]
Referring to test case 1, TViewElementsList, the page should display ALL of the main elements in red text. The 'Earth' element is not in red colored text, but in blue.

Steps to recreate bug: From main screen titled "Welcome to Elemental!", click on 'The Elements List'. The Elements List page populates with the elements, not all in red as required in Use Case 1 Special Requirements.

Expected Result: Once the user clicks on 'The Elements List' link, the page with the elements should populate with ALL elements listed in red.

**Comment by yousefaltufiel** [comment]
the mistake was in TViewElementsList in the coding file 'list' i found out that one of the elements is colored in blue which is Earth. What i did is change the color of element Earth to red instead of blue in the coding file 'list'. After that i retested TViewElementsList and it all elements listed in red

**Comment by myerssr** [comment]
Re-test of test case TViewElementsList was successful.
